<?php

?>

<script type="text/javascript">
    //<![CDATA[
    function check() {
        new Ajax.Request('<?php echo $this->getAjaxCheckUrl() ?>', {
            method:     'get',
            onSuccess: function(transport){

            if (transport.responseText){                                
                location.reload();
            }
            }
        });
    }
    //]]>
</script>

<?php echo $this->getButtonHtml() ?>